"""Add batch_id to RevenueEvent

Revision ID: 8bfc37aa5046
Revises: 
Create Date: 2026-08-26 22:00:38.882934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bfc37aa5046'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revenue_event', sa.Column('batch_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_revenue_event_batch_id'), 'revenue_event', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revenue_event_batch_id'), table_name='revenue_event')
    op.drop_column('revenue_event', 'batch_id')
    # ### end Alembic commands ###
